{% set version = '1.2.13' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-feature
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/feature_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/feature/feature_{{ version }}.tar.gz
  sha256: 2a07ff28442cca058a3ef9ed950737f1d9266aee9d74dda090caa2b117e0131e

build:
  merge_build_host: True  # [win]
  number: 1
  # r-rgl is not available on win and osx b/c libglu dependency not available
  skip: true  # [win or osx]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ks >=1.10.0
    - r-misc3d
    - r-rgl
  run:
    - r-base
    - r-ks >=1.10.0
    - r-misc3d
    - r-rgl

test:
  commands:
    - $R -e "library('feature')"           # [not win]
    - "\"%R%\" -e \"library('feature')\""  # [win]

about:
  home: http://www.mvstat.net/tduong
  license: GPL-2 | GPL-3
  summary: Local inferential feature significance for multivariate kernel density estimation.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
