travis:
  secure:
    BINSTAR_TOKEN: YfvgMAQ7jq/gxIwtFFZ9AfAX73l4KxYrdPu/rw+bZUblvAMKIfBz0D9JhALQE+LkZQh5vGHfL7/BgvjS4TG5FsLINw9ZopMhzmKtVfk+Y8TBIaBnniXnegQ2eJGKO/F0xXs9R0bD3jYnc46+hzAyvVqIZCZg8tHTqJelKRn35W3CrpJi985rGNlItqu9TIB1alekJRKTJ4W++Wr0JtqZfKDaHqUfxjfQoPbeJoSr5PlvRts6U09xyW3sH6IvDt65QVHfe32yBJ1ECWiRplnrYEFdVgHKdCh8pDpGZxK5HIYduigW39k6vIOEdCFHugn60Yz7Qwr/Etj6JBEQxhVT0d9U4r/nTfa3OFcYXW5jW1WreGV+2eDjZedMli4oxnDFkpueMMC3e9jRPQWwwjNmnm51MRR0yicM3kQSImZse01rdy8kf8z/JIQ6Evz5mUQ1l4ylCKqgRw568u7a7XJnOdT2UNRynmDSNYqMpz5C8zFzUxYzNoi+jf6u4U0W9esas3Rb/vod4Ey6hQ+/TTY0SY1v7Bb0wudf7smvZlWSsRQQQ1UERHphiAgg6LPh0rFxbwXrUB8DX11pB/yfvAQuQJ6C3NakjURqHdmG+B1nNAVYF/7H/el4vrFaxcyp/V0vkzkOuPl8dvAYfetr26+JVPu3/+kisgNvBs7tR5BU7Fo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
